name: CI Angular

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install dependencies and build the Angular project
        run: |
          cd frontend
          ls -R
          node -v
          npm -v
          npm install
          npm run build -- --configuration=production
