name: CI Angular

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install
        working-directory: ./frontend

      - name: Build do projeto Angular
        run: npm run build -- --configuration=production
        working-directory: ./frontend